In [1]:
#This notebook mirrors the crime_rate_calculation notebook but it breaks the central community 
#into its constituent neighborhoods to determine what effect that has on our analysis.
import pandas as pd

In [2]:
crime_data_csv = "data/Clean_Crime_Data.csv"
crime_data = pd.read_csv(crime_data_csv)
neighborhood_csv = 'data/community_nbhd_pop_no_central.csv'
neighborhood_df = pd.read_csv(neighborhood_csv)
neighborhood_df = neighborhood_df.rename(columns = {'NEIGHBORHOOD':'Neighborhood', 'COMMUNITY':'Community'}) 
neighborhood_df

              Neighborhood     Community  COMMUNITY POPULATION
0                BRYN MAWR  CALHOUN-ISLE                 30487
1                    CARAG  CALHOUN-ISLE                 30487
2         CEDAR-ISLES-DEAN  CALHOUN-ISLE                 30487
3               EAST ISLES  CALHOUN-ISLE                 30487
4                     ECCO  CALHOUN-ISLE                 30487
..                     ...           ...                   ...
82            MARCY-HOLMES    UNIVERSITY                 45061
83  MID CITY INDUSTRIAL AR    UNIVERSITY                 45061
84   NICOLLET IS/EAST BANK    UNIVERSITY                 45061
85  PROSPECT PK/E RIVER RD    UNIVERSITY                 45061
86              UNIVERSITY    UNIVERSITY                 45061

[87 rows x 3 columns]

In [3]:
crime_data['Precinct'].value_counts()

3.0     28380
5.0     21333
1.0     20554
4.0     19675
2.0     14422
99.0      326
18.0       46
Name: Precinct, dtype: int64

In [4]:
crime_data['Description'].value_counts()

Other Theft                   27334
Theft from Automobile         16985
Burglary of Dwelling          13939
Automobile Theft              10881
Shoplifting                    5021
Bike Theft                     4058
Aggravated Robbery             3649
Domestic Assault               3512
Burglary of Business           3499
Assault - Dangerous Weapon     3494
Robbery of Person              2724
Theft by Swindle               1847
Criminal Sexual Conduct        1628
Theft from Person              1462
Theft - Automobile Parts       1046
Assault                         965
Theft from Building             716
Robbery of Business             572
Assault of Police Officer       448
Arson                           434
Other Automobile Theft          145
Murder                          142
On-line Theft                    67
Theft/coinop Device              53
Gas Station Drive-off            25
Pocket-Picking                   22
Petty Theft                      16
Computer Hacking                 15
Theft by Computer                14
Scrapping-Recycling Theft        13
Disarm a Police Officer           8
Looting                           2
Name: Description, dtype: int64

In [5]:
violent_crimes = ['Burglary of Dwelling', 'Aggravated Robbery', 'Domestic Assault', 'Burglary of Business',
                  'Assault - Dangerous Weapon', 'Robbery of Person', 'Criminal Sexual Conduct', 'Assault',
                  'Robbery of Business', 'Assault of Police Officer', 'Arson', 'Murder', 'Disarm a Police Officer']

crime_data

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10
1,5.0,AUTOTH,Automobile Theft,44.942254,-93.275357,LYNDALE,2014-09-28
2,5.0,THEFT,Other Theft,44.947480,-93.303384,ECCO,2014-10-24
3,3.0,BURGD,Burglary of Dwelling,44.944096,-93.222936,LONGFELLOW,2015-02-11
4,3.0,AUTOTH,Automobile Theft,44.946560,-93.248680,POWDERHORN PARK,2015-02-08
...,...,...,...,...,...,...,...
104731,5.0,AUTOTH,Automobile Theft,44.964585,-93.275292,Steven's Square - Loring Heights,2020-02-20
104732,3.0,AUTOTH,Automobile Theft,44.947613,-93.227081,Longfellow,2020-02-20
104733,3.0,AUTOTH,Automobile Theft,44.949226,-93.257578,Midtown Phillips,2020-02-20
104734,2.0,THEFT,Other Theft,44.979795,-93.237257,Marcy Holmes,2020-02-20
104735,5.0,TMVP,Theft - Automobile Parts,44.948347,-93.278808,Whittier,2020-02-20

In [6]:
offense_type = crime_data.Description.isin(violent_crimes)
crime_data['Offense Type'] = offense_type
crime_data

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10,True
1,5.0,AUTOTH,Automobile Theft,44.942254,-93.275357,LYNDALE,2014-09-28,False
2,5.0,THEFT,Other Theft,44.947480,-93.303384,ECCO,2014-10-24,False
3,3.0,BURGD,Burglary of Dwelling,44.944096,-93.222936,LONGFELLOW,2015-02-11,True
4,3.0,AUTOTH,Automobile Theft,44.946560,-93.248680,POWDERHORN PARK,2015-02-08,False
...,...,...,...,...,...,...,...,...
104731,5.0,AUTOTH,Automobile Theft,44.964585,-93.275292,Steven's Square - Loring Heights,2020-02-20,False
104732,3.0,AUTOTH,Automobile Theft,44.947613,-93.227081,Longfellow,2020-02-20,False
104733,3.0,AUTOTH,Automobile Theft,44.949226,-93.257578,Midtown Phillips,2020-02-20,False
104734,2.0,THEFT,Other Theft,44.979795,-93.237257,Marcy Holmes,2020-02-20,False
104735,5.0,TMVP,Theft - Automobile Parts,44.948347,-93.278808,Whittier,2020-02-20,False

In [7]:
crime_data['Offense Type'] = crime_data['Offense Type'].replace({True:'Violent', False:'Non-Violent'})
crime_data

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10,Violent
1,5.0,AUTOTH,Automobile Theft,44.942254,-93.275357,LYNDALE,2014-09-28,Non-Violent
2,5.0,THEFT,Other Theft,44.947480,-93.303384,ECCO,2014-10-24,Non-Violent
3,3.0,BURGD,Burglary of Dwelling,44.944096,-93.222936,LONGFELLOW,2015-02-11,Violent
4,3.0,AUTOTH,Automobile Theft,44.946560,-93.248680,POWDERHORN PARK,2015-02-08,Non-Violent
...,...,...,...,...,...,...,...,...
104731,5.0,AUTOTH,Automobile Theft,44.964585,-93.275292,Steven's Square - Loring Heights,2020-02-20,Non-Violent
104732,3.0,AUTOTH,Automobile Theft,44.947613,-93.227081,Longfellow,2020-02-20,Non-Violent
104733,3.0,AUTOTH,Automobile Theft,44.949226,-93.257578,Midtown Phillips,2020-02-20,Non-Violent
104734,2.0,THEFT,Other Theft,44.979795,-93.237257,Marcy Holmes,2020-02-20,Non-Violent
104735,5.0,TMVP,Theft - Automobile Parts,44.948347,-93.278808,Whittier,2020-02-20,Non-Violent

In [8]:
crime_data['Neighborhood'] = crime_data['Neighborhood'].str.upper()

In [9]:
crime_data

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10,Violent
1,5.0,AUTOTH,Automobile Theft,44.942254,-93.275357,LYNDALE,2014-09-28,Non-Violent
2,5.0,THEFT,Other Theft,44.947480,-93.303384,ECCO,2014-10-24,Non-Violent
3,3.0,BURGD,Burglary of Dwelling,44.944096,-93.222936,LONGFELLOW,2015-02-11,Violent
4,3.0,AUTOTH,Automobile Theft,44.946560,-93.248680,POWDERHORN PARK,2015-02-08,Non-Violent
...,...,...,...,...,...,...,...,...
104731,5.0,AUTOTH,Automobile Theft,44.964585,-93.275292,STEVEN'S SQUARE - LORING HEIGHTS,2020-02-20,Non-Violent
104732,3.0,AUTOTH,Automobile Theft,44.947613,-93.227081,LONGFELLOW,2020-02-20,Non-Violent
104733,3.0,AUTOTH,Automobile Theft,44.949226,-93.257578,MIDTOWN PHILLIPS,2020-02-20,Non-Violent
104734,2.0,THEFT,Other Theft,44.979795,-93.237257,MARCY HOLMES,2020-02-20,Non-Violent
104735,5.0,TMVP,Theft - Automobile Parts,44.948347,-93.278808,WHITTIER,2020-02-20,Non-Violent

In [10]:
crime_data.to_csv("data/new_crime_data_no_central.csv", index=False, header=True)

In [11]:
new_crime = crime_data.replace({"STEVEN'S SQUARE - LORING HEIGHTS":'STEVENS SQ/LORING HGTS',
                        'STEVENS SQUARE - LORING HEIGHTS':'STEVENS SQ/LORING HGTS',
                        'BRYN - MAWR':'BRYN MAWR',
                        'CEDAR RIVERSIDE':'CEDAR RSIDE/WEST BANK',
                        'NORTH LOOP':'NORTHLOOP',
                        'SUMNER - GLENWOOD':'SUMNER-GLENWOOD',
                        'PROSPECT PARK - EAST RIVER ROAD':'PROSPECT PK/E RIVER RD',
                        'WILLARD - HAY':'WILLARD-HAY',
                        'MID - CITY INDUSTRIAL':'MID CITY INDUSTRIAL AR',
                        'LIND - BOHANON':'LIND-BOHANON',
                        'NICOLLET ISLAND - EAST BANK':'NICOLLET IS/EAST BANK',
                        'ST. ANTHONY EAST':'ST ANTHONY EAST',
                        'WEBBER - CAMDEN':'WEBBER-CAMDEN',
                        'CEDAR - ISLES - DEAN':'CEDAR-ISLES-DEAN',
                        'ST. ANTHONY WEST':'ST ANTHONY WEST',
                        'CAMDEN INDUSTRIAL':'CAMDEN INDUSTRIAL AREA',
                        'HUMBOLDT INDUSTRIAL AREA':'HUMBOLDT INDUST AREA',
                        'MARCY HOLMES':'MARCY-HOLMES'
                       })

In [12]:
len(new_crime['Neighborhood'].unique())

87

In [13]:
neighborhood_crime = pd.merge(new_crime, neighborhood_df, how='outer', on='Neighborhood')

In [14]:
neighborhood_crime.dropna(how='any')

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type,Community,COMMUNITY POPULATION
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10,Violent,NORTHEAST,38226.0
1,2.0,TFMV,Theft from Automobile,45.001986,-93.263852,SHERIDAN,2015-02-16,Non-Violent,NORTHEAST,38226.0
2,2.0,TFMV,Theft from Automobile,45.001984,-93.258895,SHERIDAN,2015-02-16,Non-Violent,NORTHEAST,38226.0
3,2.0,THEFT,Other Theft,45.001442,-93.263086,SHERIDAN,2015-02-22,Non-Violent,NORTHEAST,38226.0
4,2.0,CSCR,Criminal Sexual Conduct,45.000354,-93.266146,SHERIDAN,2015-01-24,Violent,NORTHEAST,38226.0
...,...,...,...,...,...,...,...,...,...,...
104731,4.0,BURGD,Burglary of Dwelling,45.041363,-93.299191,HUMBOLDT INDUST AREA,2019-12-25,Violent,CAMDEN,30586.0
104732,4.0,AUTOTH,Automobile Theft,45.043940,-93.309872,HUMBOLDT INDUST AREA,2019-09-08,Non-Violent,CAMDEN,30586.0
104733,4.0,THEFT,Other Theft,45.043939,-93.308607,HUMBOLDT INDUST AREA,2019-08-12,Non-Violent,CAMDEN,30586.0
104734,4.0,TFMV,Theft from Automobile,45.039897,-93.299109,HUMBOLDT INDUST AREA,2019-01-10,Non-Violent,CAMDEN,30586.0
104735,4.0,BURGB,Burglary of Business,45.039897,-93.299109,HUMBOLDT INDUST AREA,2019-11-17,Violent,CAMDEN,30586.0

In [15]:
downtowneast_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'DOWNTOWN EAST'])
downtownwest_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'DOWNTOWN WEST'])
elliotpark_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'ELLIOT PARK'])
loringpark_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'LORING PARK'])
northloop_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'DOWNTOWN EAST'])
stevenssq_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'STEVENS SQ/LORING HGTS'])
calhoun_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'CALHOUN-ISLE'])
camden_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'CAMDEN'])
longfellow_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'LONGFELLOW'])
nearnorth_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'NEAR NORTH'])
nokomis_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'NOKOMIS'])
northeast_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'NORTHEAST'])
phillips_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'PHILLIPS'])
powderhorn_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'POWDERHORN'])
southwest_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'SOUTHWEST'])
university_crime = len(neighborhood_crime.loc[neighborhood_crime['Community'] == 'UNIVERSITY'])

total_crime = [calhoun_crime, camden_crime, downtowneast_crime, downtownwest_crime, elliotpark_crime, loringpark_crime,
               northloop_crime, stevenssq_crime, longfellow_crime, nearnorth_crime, nokomis_crime, 
               northeast_crime, phillips_crime, powderhorn_crime, southwest_crime, university_crime]

In [16]:
calhoun_pop = 30487
camden_pop = 30586
downtowneast_pop = 1254
dowtownwest_pop = 7466
elliotpark_pop = 6596
loringpark_pop = 8835
northloop_pop = 5760
stevenssq_pop = 4031
longfellow_pop = 28490
nearnorth_pop = 34902
nokomis_pop = 38503
northeast_pop = 38226
phillips_pop = 22433
powderhorn_pop = 58154
southwest_pop = 49820
university_pop = 45061

population = [calhoun_pop, camden_pop, downtowneast_pop, dowtownwest_pop, elliotpark_pop, loringpark_pop, 
              northloop_pop, stevenssq_pop, longfellow_pop, nearnorth_pop, nokomis_pop, northeast_pop,
              phillips_pop, powderhorn_pop, southwest_pop, university_pop]

In [17]:
neighborhood_crime.to_csv("data/neighborhood_crime_no_central.csv", index=True, header=True)

In [18]:
neighborhood_group = neighborhood_crime.groupby('Community')
neighborhood_group.count()

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type,COMMUNITY POPULATION
Community,,,,,,,,,
CALHOUN-ISLE,8893,8893,8893,8893,8893,8893,8893,8893,8893
CAMDEN,7916,7916,7916,7916,7916,7916,7916,7916,7916
DOWNTOWN EAST,990,990,990,990,990,990,990,990,990
DOWNTOWN WEST,11306,11306,11306,11306,11306,11306,11306,11306,11306
ELLIOT PARK,1978,1978,1978,1978,1978,1978,1978,1978,1978
LONGFELLOW,8612,8612,8612,8612,8612,8612,8612,8612,8612
LORING PARK,2425,2425,2425,2425,2425,2425,2425,2425,2425
NEAR NORTH,8660,8660,8660,8660,8660,8661,8660,8660,8661
NOKOMIS,5164,5164,5164,5164,5164,5164,5164,5164,5164
NORTHEAST,6628,6628,6628,6628,6628,6629,6628,6628,6629
NORTHLOOP,2066,2066,2066,2066,2066,2066,2066,2066,2066
PHILLIPS,7211,7211,7211,7211,7211,7211,7211,7211,7211
POWDERHORN,13741,13741,13741,13741,13741,13741,13741,13741,13741
SOUTHWEST,5625,5625,5625,5625,5625,5625,5625,5625,5625
STEVENS SQ/LORING HGTS,1074,1074,1074,1074,1074,1074,1074,1074,1074
UNIVERSITY,8995,8995,8995,8995,8995,8996,8995,8995,8996

In [19]:
violent_crime = neighborhood_crime.loc[neighborhood_crime['Offense Type'] == 'Violent']
violent_crime

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type,Community,COMMUNITY POPULATION
0,2.0,BURGD,Burglary of Dwelling,45.003332,-93.268892,SHERIDAN,2015-02-10,Violent,NORTHEAST,38226.0
4,2.0,CSCR,Criminal Sexual Conduct,45.000354,-93.266146,SHERIDAN,2015-01-24,Violent,NORTHEAST,38226.0
5,2.0,BURGD,Burglary of Dwelling,45.005276,-93.263861,SHERIDAN,2015-02-24,Violent,NORTHEAST,38226.0
7,2.0,BURGD,Burglary of Dwelling,45.006012,-93.270889,SHERIDAN,2015-01-27,Violent,NORTHEAST,38226.0
8,2.0,BURGD,Burglary of Dwelling,45.001148,-93.268964,SHERIDAN,2015-01-28,Violent,NORTHEAST,38226.0
...,...,...,...,...,...,...,...,...,...,...
104725,4.0,BURGD,Burglary of Dwelling,45.044847,-93.307999,HUMBOLDT INDUST AREA,2017-01-28,Violent,CAMDEN,30586.0
104726,4.0,BURGB,Burglary of Business,45.043940,-93.309872,HUMBOLDT INDUST AREA,2018-05-21,Violent,CAMDEN,30586.0
104727,4.0,BURGB,Burglary of Business,45.043949,-93.314965,HUMBOLDT INDUST AREA,2018-06-27,Violent,CAMDEN,30586.0
104731,4.0,BURGD,Burglary of Dwelling,45.041363,-93.299191,HUMBOLDT INDUST AREA,2019-12-25,Violent,CAMDEN,30586.0
104735,4.0,BURGB,Burglary of Business,45.039897,-93.299109,HUMBOLDT INDUST AREA,2019-11-17,Violent,CAMDEN,30586.0

In [20]:
violent_downtowneast_crime = len(violent_crime.loc[violent_crime['Community'] == 'DOWNTOWN EAST'])
violent_downtownwest_crime = len(violent_crime.loc[violent_crime['Community'] == 'DOWNTOWN WEST'])
violent_elliotpark_crime = len(violent_crime.loc[violent_crime['Community'] == 'ELLIOT PARK'])
violent_loringpark_crime = len(violent_crime.loc[violent_crime['Community'] == 'LORING PARK'])
violent_northloop_crime = len(violent_crime.loc[violent_crime['Community'] == 'DOWNTOWN EAST'])
violent_stevenssq_crime = len(violent_crime.loc[violent_crime['Community'] == 'STEVENS SQ/LORING HGTS'])
violent_calhoun_crime = len(violent_crime.loc[violent_crime['Community'] == 'CALHOUN-ISLE'])
violent_camden_crime = len(violent_crime.loc[violent_crime['Community'] == 'CAMDEN'])
violent_longfellow_crime = len(violent_crime.loc[violent_crime['Community'] == 'LONGFELLOW'])
violent_nearnorth_crime = len(violent_crime.loc[violent_crime['Community'] == 'NEAR NORTH'])
violent_nokomis_crime = len(violent_crime.loc[violent_crime['Community'] == 'NOKOMIS'])
violent_northeast_crime = len(violent_crime.loc[violent_crime['Community'] == 'NORTHEAST'])
violent_phillips_crime = len(violent_crime.loc[violent_crime['Community'] == 'PHILLIPS'])
violent_powderhorn_crime = len(violent_crime.loc[violent_crime['Community'] == 'POWDERHORN'])
violent_southwest_crime = len(violent_crime.loc[violent_crime['Community'] == 'SOUTHWEST'])
violent_university_crime = len(violent_crime.loc[violent_crime['Community'] == 'UNIVERSITY'])

violent_crime_stat = [violent_calhoun_crime, violent_camden_crime, violent_downtowneast_crime, violent_downtownwest_crime,
                      violent_elliotpark_crime, violent_loringpark_crime, violent_northloop_crime, violent_stevenssq_crime,
                      violent_longfellow_crime, violent_nearnorth_crime, violent_nokomis_crime, violent_northeast_crime,
                      violent_phillips_crime, violent_powderhorn_crime, violent_southwest_crime, violent_university_crime]

In [21]:
nonviolent_crime = neighborhood_crime.loc[neighborhood_crime['Offense Type'] == 'Non-Violent']
nonviolent_crime

,Precinct,Offense,Description,Latitude,Longitude,Neighborhood,Date of Offense,Offense Type,Community,COMMUNITY POPULATION
1,2.0,TFMV,Theft from Automobile,45.001986,-93.263852,SHERIDAN,2015-02-16,Non-Violent,NORTHEAST,38226.0
2,2.0,TFMV,Theft from Automobile,45.001984,-93.258895,SHERIDAN,2015-02-16,Non-Violent,NORTHEAST,38226.0
3,2.0,THEFT,Other Theft,45.001442,-93.263086,SHERIDAN,2015-02-22,Non-Violent,NORTHEAST,38226.0
6,2.0,AUTOTH,Automobile Theft,45.002543,-93.271162,SHERIDAN,2014-11-21,Non-Violent,NORTHEAST,38226.0
9,2.0,THEFT,Other Theft,44.999257,-93.263099,SHERIDAN,2015-01-31,Non-Violent,NORTHEAST,38226.0
...,...,...,...,...,...,...,...,...,...,...
104729,4.0,THEFT,Other Theft,45.039897,-93.299109,HUMBOLDT INDUST AREA,2019-06-29,Non-Violent,CAMDEN,30586.0
104730,4.0,AUTOTH,Automobile Theft,45.043940,-93.309872,HUMBOLDT INDUST AREA,2019-05-08,Non-Violent,CAMDEN,30586.0
104732,4.0,AUTOTH,Automobile Theft,45.043940,-93.309872,HUMBOLDT INDUST AREA,2019-09-08,Non-Violent,CAMDEN,30586.0
104733,4.0,THEFT,Other Theft,45.043939,-93.308607,HUMBOLDT INDUST AREA,2019-08-12,Non-Violent,CAMDEN,30586.0
104734,4.0,TFMV,Theft from Automobile,45.039897,-93.299109,HUMBOLDT INDUST AREA,2019-01-10,Non-Violent,CAMDEN,30586.0

In [23]:
nonviolent_downtowneast_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'DOWNTOWN EAST'])
nonviolent_downtownwest_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'DOWNTOWN WEST'])
nonviolent_elliotpark_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'ELLIOT PARK'])
nonviolent_loringpark_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'LORING PARK'])
nonviolent_northloop_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'DOWNTOWN EAST'])
nonviolent_stevenssq_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'STEVENS SQ/LORING HGTS'])
nonviolent_calhoun_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'CALHOUN-ISLE'])
nonviolent_camden_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'CAMDEN'])
nonviolent_longfellow_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'LONGFELLOW'])
nonviolent_nearnorth_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'NEAR NORTH'])
nonviolent_nokomis_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'NOKOMIS'])
nonviolent_northeast_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'NORTHEAST'])
nonviolent_phillips_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'PHILLIPS'])
nonviolent_powderhorn_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'POWDERHORN'])
nonviolent_southwest_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'SOUTHWEST'])
nonviolent_university_crime = len(nonviolent_crime.loc[nonviolent_crime['Community'] == 'UNIVERSITY'])

nonviolent_crime_stat = [nonviolent_calhoun_crime, nonviolent_camden_crime, nonviolent_downtowneast_crime, 
                         nonviolent_downtownwest_crime, nonviolent_elliotpark_crime, nonviolent_loringpark_crime, 
                         nonviolent_northloop_crime, nonviolent_stevenssq_crime, nonviolent_longfellow_crime, 
                         nonviolent_nearnorth_crime, nonviolent_nokomis_crime, nonviolent_northeast_crime, 
                         nonviolent_phillips_crime, nonviolent_powderhorn_crime, nonviolent_southwest_crime, 
                         nonviolent_university_crime]

In [26]:
community = ['Calhoun-Isle', 'Camden', 'Downtown East', 'Downtown West', 'Elliot Park', 'Loring Park', 'North Loop',
             "Steven's Square/Loring Heights", 'Longfellow', 'Near North', 'Nokomis', 'North East', 'Phillips',
             'Powderhorn', 'Southwest', 'University']

In [27]:
summary_crime = pd.DataFrame({'Community':community, 'Population':population, 'Total Crime':total_crime,
                              'Violent Crime':violent_crime_stat, 'Non-Violent Crime':nonviolent_crime_stat,
                              'Total Crime Rate':'', 'Violent Crime Rate':'', 'Non-Violent Crime Rate':''})
summary_crime

,Community,Population,Total Crime,Violent Crime,Non-Violent Crime,Total Crime Rate,Violent Crime Rate,Non-Violent Crime Rate
0,Calhoun-Isle,30487,8893,2079,6814,,,
1,Camden,30586,7916,3966,3950,,,
2,Downtown East,1254,990,119,871,,,
3,Downtown West,7466,11306,2257,9049,,,
4,Elliot Park,6596,1978,618,1360,,,
5,Loring Park,8835,2425,645,1780,,,
6,North Loop,5760,990,119,871,,,
7,Steven's Square/Loring Heights,4031,1074,393,681,,,
8,Longfellow,28490,8612,2331,6281,,,
9,Near North,34902,8661,4203,4457,,,
10,Nokomis,38503,5164,2115,3049,,,
11,North East,38226,6629,2117,4511,,,
12,Phillips,22433,7211,2935,4276,,,
13,Powderhorn,58154,13741,5361,8380,,,
14,Southwest,49820,5625,1844,3781,,,
15,University,45061,8996,2383,6612,,,

In [28]:
#Total crime statistics are an aggregation of 5 years of crime data.  I want to get a crime rate for every 1,000 people 
#per year.  So normally I would divide the number of crimes by the population and multiply by 1000 to get the rate 
#per 1000 people.  But because I have five years of crime data, I mulitplied by 200.
summary_crime['Total Crime Rate'] = round(summary_crime['Total Crime']/summary_crime['Population']*200,2)
summary_crime['Violent Crime Rate'] = round(summary_crime['Violent Crime']/summary_crime['Population']*200,2)
summary_crime['Non-Violent Crime Rate'] = round(summary_crime['Non-Violent Crime']/summary_crime['Population']*200,2)
summary_crime

,Community,Population,Total Crime,Violent Crime,Non-Violent Crime,Total Crime Rate,Violent Crime Rate,Non-Violent Crime Rate
0,Calhoun-Isle,30487,8893,2079,6814,58.34,13.64,44.70
1,Camden,30586,7916,3966,3950,51.76,25.93,25.83
2,Downtown East,1254,990,119,871,157.89,18.98,138.92
3,Downtown West,7466,11306,2257,9049,302.87,60.46,242.41
4,Elliot Park,6596,1978,618,1360,59.98,18.74,41.24
5,Loring Park,8835,2425,645,1780,54.90,14.60,40.29
6,North Loop,5760,990,119,871,34.38,4.13,30.24
7,Steven's Square/Loring Heights,4031,1074,393,681,53.29,19.50,33.79
8,Longfellow,28490,8612,2331,6281,60.46,16.36,44.09
9,Near North,34902,8661,4203,4457,49.63,24.08,25.54
10,Nokomis,38503,5164,2115,3049,26.82,10.99,15.84
11,North East,38226,6629,2117,4511,34.68,11.08,23.60
12,Phillips,22433,7211,2935,4276,64.29,26.17,38.12
13,Powderhorn,58154,13741,5361,8380,47.26,18.44,28.82
14,Southwest,49820,5625,1844,3781,22.58,7.40,15.18
15,University,45061,8996,2383,6612,39.93,10.58,29.35

In [29]:
summary_crime.to_csv("data/summary_crime_no_central.csv", index=True, header=True)